### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by MRacingRU** [ultramarine11/wireless-industry#4]
`---- Minecraft Crash Report ----

WARNING: coremods are present:
  MixinBooter (!mixinbooter-4.2.jar)
  MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
  SteveKunGLibPlugin (SteveKunG's-Lib-1.12.2-1.2.0.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.280.jar)
Contact their authors BEFORE contacting forge

// Daisy, daisy...

Time: 24.03.22 0:09
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Wireless Industry (wirelesstools)
Caused by: java.lang.NoClassDefFoundError: ic2/core/block/IInventorySlotHolder
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Unknown Source)
	at java.lang.Class.getConstructor0(Unknown Source)
	at java.lang.Class.newInstance(Unknown Source)
	at ru.wirelesstools.tileentities.othertes.EnumOtherTEs.buildDummies(EnumOtherTEs.java:135)
	at ru.wirelesstools.MainWI.init(MainWI.java:127)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:724)
	at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:112)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:342)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:269)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:688)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: ic2.core.block.IInventorySlotHolder
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:223)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 41 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Magma Version: 32e7e1a-DEV
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_321, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 528966248 bytes (504 MB) / 1044447232 bytes (996 MB) up to 6329073664 bytes (6035 MB)
	JVM Flags: 7 total; -Xincgc -XX:+CMSClassUnloadingEnabled -Xnoclassgc -XX:UseSSE=3 -Xincgc -Xmx6144M -Xms1024M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 36 mods loaded, 36 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                    | Version           | Source                                          | Signature                                |
	|:----- |:--------------------- |:----------------- |:----------------------------------------------- |:---------------------------------------- |
	| LCHI  | minecraft             | 1.12.2            | minecraft.jar                                   | None                                     |
	| LCHI  | mcp                   | 9.42              | minecraft.jar                                   | None                                     |
	| LCHI  | FML                   | 8.0.99.99         | CORE_MAGMA_88f081a_DEV_SERVER_1.12.2.jar        | None                                     |
	| LCHI  | forge                 | 14.23.5.2860      | CORE_MAGMA_88f081a_DEV_SERVER_1.12.2.jar        | None                                     |
	| LCHI  | micdoodlecore         |                   | minecraft.jar                                   | None                                     |
	| LCHI  | mixinbooter           | 4.2               | minecraft.jar                                   | None                                     |
	| LCHI  | ic2                   | 2.8.170-ex112     | industrialcraft-2-2.8.170-ex112.jar             | de041f9f6187debbc77034a344134053277aa3b0 |
	| LCHI  | advanced_machines     | 61.0.1            | Advanced+Machines-61.0.1.jar                    | None                                     |
	| LCHI  | advanced_solar_panels | 4.3.0             | Advanced+Solar+Panels-4.3.0.jar                 | None                                     |
	| LCHI  | appliedenergistics2   | rv6-stable-7      | appliedenergistics2-rv6-stable-7.jar            | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
	| LCHI  | codechickenlib        | 3.2.3.358         | CodeChickenLib-1.12.2-3.2.3.358-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHI  | redstoneflux          | 2.1.1             | RedstoneFlux-1.12-2.1.1.1-universal.jar         | None                                     |
	| LCHI  | cofhcore              | 4.6.6             | CoFHCore-1.12.2-4.6.6.1-universal.jar           | None                                     |
	| LCHI  | cofhworld             | 1.4.0             | CoFHWorld-1.12.2-1.4.0.1-universal.jar          | None                                     |
	| LCHI  | comboarmors           | 1.12.2-0.0.9      | ComboArmors-1.12.2-0.0.9.jar                    | None                                     |
	| LCHI  | crafttweaker          | 4.1.20            | CraftTweaker2-1.12-4.1.20.674.jar               | None                                     |
	| LCHI  | crafttweakerjei       | 2.0.3             | CraftTweaker2-1.12-4.1.20.674.jar               | None                                     |
	| LCHI  | energycontrol         | 1.12.2-0.2.7      | EnergyControl-1.12.2-0.2.7.jar                  | None                                     |
	| LCHI  | extracells            | 2.6.7             | ExtraCells-1.12.2-2.6.7.jar                     | None                                     |
	| LCHI  | galacticraftcore      | 4.0.2.280         | GalacticraftCore-1.12.2-4.0.2.280.jar           | None                                     |
	| LCHI  | galacticraftplanets   | 4.0.2.280         | Galacticraft-Planets-1.12.2-4.0.2.280.jar       | None                                     |
	| LCHI  | gravisuite            | 3.1.1             | Gravitation+Suite-3.1.1.jar                     | None                                     |
	| LCHI  | ironchest             | 1.12.2-7.0.67.844 | ironchest_1.12.2_7.0.72.847.jar                 | None                                     |
	| LCHI  | mekanism              | 1.12.2-9.8.3.390  | Mekanism-1.12.2-9.8.3.390.jar                   | None                                     |
	| LCHI  | mekanismgenerators    | 1.12.2-9.8.3.390  | MekanismGenerators-1.12.2-9.8.3.390.jar         | None                                     |
	| LCHI  | mekanismtools         | 1.12.2-9.8.3.390  | MekanismTools-1.12.2-9.8.3.390.jar              | None                                     |
	| LCHI  | stevekung's_lib       | 1.2.0             | SteveKunG's-Lib-1.12.2-1.2.0.jar                | None                                     |
	| LCHI  | moreplanets           | 2.2.2             | More-Planets-1.12.2-2.2.2-GC280.jar             | None                                     |
	| LCHI  | thermalfoundation     | 2.6.7             | ThermalFoundation-1.12.2-2.6.7.1-universal.jar  | None                                     |
	| LCHI  | thermalexpansion      | 5.5.7             | ThermalExpansion-1.12.2-5.5.7.1-universal.jar   | None                                     |
	| LCHI  | redstonearsenal       | 2.6.6             | RedstoneArsenal-1.12.2-2.6.6.1-universal.jar    | None                                     |
	| LCHI  | thermaldynamics       | 2.5.6             | ThermalDynamics-1.12.2-2.5.6.1-universal.jar    | None                                     |
	| LCHI  | simplyjetpacks        | 1.12.2-2.2.20.0   | SimplyJetpacks2-1.12.2-2.2.20.0.jar             | None                                     |
	| LCHI  | thermalcultivation    | 0.3.6             | ThermalCultivation-1.12.2-0.3.6.1-universal.jar | None                                     |
	| LCHI  | thermalinnovation     | 0.3.6             | ThermalInnovation-1.12.2-0.3.6.1-universal.jar  | None                                     |
	| LCHE  | wirelesstools         | 1.1.10            | wireless-industry-1.12.2-1.1.10-release.jar     | None                                     |

	Loaded coremods (and transformers): 
MixinBooter (!mixinbooter-4.2.jar)
  
MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
  mekanism.coremod.KeybindingMigrationHelper
SteveKunGLibPlugin (SteveKunG's-Lib-1.12.2-1.2.0.jar)
  
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.280.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
	AE2 Version: stable rv6-stable-7 for Forge 14.23.5.2768
	Profiler Position: N/A (disabled)
	Player Count: 0 / 32; []
	Is Modded: Definitely; Server brand changed to 'Magma'
	Type: Dedicated Server (map_server.txt)`

**Comment by ultramarine11** [comment]
The root of the problem lies in the IC2.
Please update IC2 to the latest version (industrialcraft-2-2.8.221-ex112)

**Comment by ultramarine11** [comment]
Я уже встречал подобную шнягу со старыми версиями ик2.
У меня используется последняя (которую я выше написал) и всё норм работает

**Comment by MRacingRU** [comment]
Ну ваще-то, ваще-то, у меня стоит последняя версия ик2...

**Comment by ultramarine11** [comment]
Нет, судя по крашлогу, у вас 2.8.170-ex112, а последняя - это 2.8.221-ex112. Посмотрите внимательно на курсфордже
